# Generated by Django 4.1.7 on 2023-03-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hehe',
        ),
    ]
